site_name: emeh-protocols
pages:
- ['index.md', 'Home']
- ['contributing.md', 'Contributing']
- ['license.md', 'License']
- ['Supplement_1.1_Species_used.md', '1. Materials', '1.1 Species used']
theme: readthedocs